server:
  port: 8005
  servlet:
    context-path: /tansci/

spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail: # 邮件配置
    # 配置 SMTP 服务器地址 （smtp.126.com（端口：465、994），smtp.163.com（端口：465、994），smtp.yeah.net（端口：465、994），smtp.qq.com（端口：465、587））
    host: smtp.qq.com
    # 发送者邮箱
    username: 742354529@qq.com
    # 配置密码，注意不是真正的密码，是申请的授权码
    password: gfrgcjrlazprbaaa
    # 端口
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 版本号
version: 1.1.0

# 阿里云短信配置
sms:
  access-id: LTgfdgQfjF6fdgL4BfdgCHoH
  access-key: dsfg4WxAits5MdYgdfgVAYfGfg
  sign-name: TANSCI
  endpoint: dysmsapi.aliyuncs.com

# 三方授权信息
authorized:
  wechat: # 微信开放平台信息
    app_id: 1000001  # appid
    app_secret: 1000001  # appsecret
    base_url: https://open.weixin.qq.com/connect/oauth2/authorize  # 微信开放平台授权baseUrl
    base_access_token_url: https://api.weixin.qq.com/sns/oauth2/access_token # 微信开放平台获取token
    base_user_info_url: https://api.weixin.qq.com/sns/userinfo # 微信开放平台获取用户信息
    redirect_url: http://127.0.0.1/tansci/auth/wxCallback  # 重定向ur